spring:
  rabbitmq:
    addresses: 127.0.0.1:6672
    username: guest
    password: guest
    virtual-host: /springcloud-sell
    connection-timeout: 15000
  redis:
    host: localhost
    port: 7379
eureka:
  client:
    service-url:
      defaultZone: http://eureka9901:9901/eureka/,http://eureka9902:9902/eureka/,http://eureka9903:9903/eureka/
    register-with-eureka: true
    fetch-registry: true
