spring:
  rabbitmq:
    addresses: 127.0.0.1:6672
    username: guest
    password: guest
    virtual-host: /springcloud-sell
    connection-timeout: 15000
  redis:
    host: localhost
    port: 7379
