eureka:
  client:
    service-url:
      defaultZone: http://eureka9901:9901/eureka/,http://eureka9902:9902/eureka/,http://eureka9903:9903/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9946
spring:
  application:
    name: springcloud-sell-gateway
env: dev33
