spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: miaoqi
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka9901:9901/eureka/,http://eureka9901:9902/eureka/,http://eureka9901:9903/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9916
